wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.22.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1770282337
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 106
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 106
      3:
      - 4
      - 7
      - 13
      - 42
      - 66
      4: 3.9.19
      5: 0.22.1
      6: 4.36.2
      13: linux-x86_64
    e:
      wtl9hjkplgojd04i53ly6coqjwz8w138:
        os: Linux-4.18.0-553.40.1.el8_10.x86_64-x86_64-with-glibc2.28
        python: CPython 3.9.19
        started_at: '2026-02-05T09:05:37.185031Z'
        program: /home/dlf903/Histology_v2/Decoder/gigapath_decoder.py
        root: .
        host: hendrixgpu22fl.unicph.domain
        executable: /home/dlf903/miniconda3/envs/gigapath/bin/python
        cpu_count: 64
        cpu_count_logical: 128
        gpu_type: NVIDIA A40
        gpu_count: 1
        disk:
          /:
            total: '107321753600'
            used: '29966213120'
        memory:
          total: '2163694112768'
        gpu_nvidia:
        - name: NVIDIA A40
          memory_total: '48305799168'
          cuda_cores: 10752
          architecture: Ampere
          uuid: GPU-8fe506bb-46b3-451b-8755-dff5043cc568
        cuda_version: '12.8'
        slurm:
          job_name: gigapath
          jobid: '9388'
          job_account: students
          tasks_per_node: '1'
          submit_dir: /home/dlf903
          nodeid: '0'
          job_gid: '100'
          topology_addr: hendrixgpu22fl
          job_id: '9388'
          prio_process: '0'
          topology_addr_pattern: node
          job_qos: normal
          node_aliases: (null)
          localid: '0'
          cluster_name: dicompute
          procid: '0'
          cpus_on_node: '16'
          job_uid: '181904178'
          gtids: '0'
          job_num_nodes: '1'
          submit_host: hendrixgate01fl.unicph.domain
          job_cpus_per_node: '16'
          job_user: dlf903
          conf: /var/spool/slurmd/conf-cache/slurm.conf
          job_gpus: '2'
          nnodes: '1'
          mem_per_node: '65536'
          job_nodelist: hendrixgpu22fl
          task_pid: '1221065'
          cpus_per_task: '16'
          nodelist: hendrixgpu22fl
          working_cluster: dicompute:hendrixhead01fl.unicph.domain:6817:9216:109
          job_partition: gpu
        writer_id: wtl9hjkplgojd04i53ly6coqjwz8w138
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy
      5: 1
      6:
      - 1
input_dim:
  desc: null
  value: 6144
num_classes:
  desc: null
  value: 6
task_type:
  desc: null
  value: multiclass
lr:
  desc: null
  value: 0.0001
dropout:
  desc: null
  value: 0.5
class_weights:
  desc: null
  value: tensor([0.0385, 0.0478, 0.0239, 0.0255, 0.0752, 0.7892])
